sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /head_camera/depth_downsample/points
    # filtered_cloud_topic: filtered_cloud
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.05
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud


    min_sensor_dist: 1.5
    self_see_default_padding: .04
    # annotate: -1.0
    self_see_default_scale: 1.0
    self_see_links:
      - name: gripper_link
        padding: 0.1
      - name: wrist_roll_link
        padding: 0.1
      - name: wrist_flex_link
        padding: 0.1
      - name: forearm_roll_link
        padding: 0.1
      - name: elbow_flex_link
        padding: 0.1
      - name: upperarm_roll_link
        padding: 0.1
      - name: shoulder_lift_link
        padding: 0.1
      - name: shoulder_pan_link
        padding: 0.1
      - name: torso_lift_link
        padding: 0.1
      - name: base_link
        padding: 0.1

